### ISSUE TITLE
~/.mcabal/mhs-0.9.11.0/packages: getDirectoryContents:openDirStream: does not exist

### ISSUE THREAD

**Issue by juhp** [augustss/MicroCabal#7]
```
$ mcabal install simple-cmd
Building in /var/home/petersen/.mcabal/packages/simple-cmd-0.2.7
Building library simple-cmd
mcabal: /var/home/petersen/.mcabal/mhs-0.9.11.0/packages: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

(also this is actually 0.9.13.0 : - )

**Comment by juhp** [comment]
Btw perhaps some simple working example could be mentioned in the readme?
since it is still hard to tell what works so far.

**Comment by augustss** [comment]
Good idea.
MicroCabal needs some love. :)

**Comment by augustss** [comment]
I've done some more testing&fixing of mcabal, building with ghc. It works to install packages like lens and ad, so it's a lot better than before.

**Comment by augustss** [comment]
I think this works now,
