### ISSUE TITLE
Lacking installDir doesn't seem to work

### ISSUE THREAD

**Issue by ysangkok** [augustss/MicroCabal#8]
MicroCabal is passing `-Q` without installDir, which should work, but for me, it calls `head (pkgPath flags)` which seems to error (applying the patch at the end of the post)

```
 % mhs -Q parsec-2.1.0.1.pkg
mhs: error: pkgPath is empty: []
```

Apparently this is because the pkgPath setting in the beginning of the `main` function didn't work, so it fell back to the line ending with `[] -- No package search path`.

It works if I pass use `mhs -Q parsec-2.1.0.1.pkg -a /home/janus/.mcabal/mhs-0.9.15.0`.

Reporting this because it took a while to debug so I am wondering whether the following patch with an error message might make sense to add.

```diff
diff --git a/src/MicroHs/Main.hs b/src/MicroHs/Main.hs
index 122b11b..cff9f8b 100644
--- a/src/MicroHs/Main.hs
+++ b/src/MicroHs/Main.hs
@@ -257,7 +257,10 @@ mainInstallPackage flags [pkgfn, dir] = do
         createDirectoryIfMissing True d
         writeFile fn pkgout
   mapM_ mk (pkgExported pkg)
-mainInstallPackage flags [pkgfn] = mainInstallPackage flags [pkgfn, head (pkgPath flags)]
+mainInstallPackage flags [pkgfn] =
+  case pkgPath flags of
+    [] -> error $ "pkgPath is empty: " <> show (pkgPath flags)
+    first:_ -> mainInstallPackage flags [pkgfn, first]
 mainInstallPackage _ _ = error usage
```

**Comment by augustss** [comment]
Thanks.  I've made the change.
